# Generates a self-signed SSL certificate for local development
# Requires: OpenSSL installed (or use the embedded Windows option)
#
# For production: use Let's Encrypt (certbot) instead.
#
# Usage: .\docker\nginx\generate-cert.ps1

$certsDir = Join-Path (Split-Path $PSScriptRoot -Parent) "docker\nginx\certs"

if (-not (Test-Path $certsDir)) {
    New-Item -ItemType Directory -Path $certsDir -Force | Out-Null
    Write-Host "✓ Created directory: $certsDir"
}

$crtPath = Join-Path $certsDir "ticketprime.crt"
$keyPath = Join-Path $certsDir "ticketprime.key"

if ((Test-Path $crtPath) -and (Test-Path $keyPath)) {
    Write-Host "✓ Certificates already exist at: $certsDir"
    exit 0
}

# Try to use OpenSSL first
$openssl = Get-Command "openssl" -ErrorAction SilentlyContinue

if ($openssl) {
    Write-Host "Generating self-signed certificate using OpenSSL..."
    
    & openssl req -x509 -nodes -days 365 -newkey rsa:2048 `
        -keyout $keyPath `
        -out $crtPath `
        -subj "/CN=ticketprime.local/O=TicketPrime/C=BR" `
        -addext "subjectAltName=DNS:ticketprime.local,DNS:localhost,IP:127.0.0.1"
    
    Write-Host "✓ Certificate generated:"
    Write-Host "  CRT: $crtPath"
    Write-Host "  KEY: $keyPath"
} else {
    Write-Host "OpenSSL not found. Install OpenSSL or use the .NET dev-cert approach."
    Write-Host ""
    Write-Host "Option 1: Install OpenSSL from https://slproweb.com/products/Win32OpenSSL.html"
    Write-Host "Option 2: Use 'dotnet dev-certs https --export-path ./cert.pfx' and convert manually."
    Write-Host ""
    Write-Host "For now, creating placeholder files. Replace with real certificates before deployment."
    
    # Create placeholder
    @"
Placeholder self-signed certificate.
Replace with real SSL certificate for production deployment.
Generated by: docker/nginx/generate-cert.ps1
"@ | Set-Content $crtPath -Encoding UTF8
    
    @"
Placeholder private key.
Replace with real SSL private key for production deployment.
Generated by: docker/nginx/generate-cert.ps1
"@ | Set-Content $keyPath -Encoding UTF8
    
    Write-Host "⚠ Placeholder files created. Replace with real certificates before using HTTPS."
}
